[tool.ruff.lint]
ignore = [
    "D",  # docstring
    "RUF002",  # ambiguous unicode characters
    "S311",  # pseudo-random
]
select = ["ALL"]
exclude = [
    "tests/",
    "test_*.py",
    "*_test.py",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
