name: Deploy bot

on:
  push:
    branches:
      - feature-mvp

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_NL_PRIVATE_KEY }}
          script: |
            set -e

            cd /${{ secrets.USER }}/workspace/aaa-xoxo-tgbot

            echo "Pull latest code..."
            git pull origin feature-mvp

            # папка для SQLite (если ещё нет)
            mkdir -p data

            echo "Stop old container..."
            docker stop xoxo_bot || true
            docker rm xoxo_bot || true

            echo "Build new image..."
            docker build -t xoxo_bot .

            echo "Run container with SQLite volume..."
            docker run -d \
              --name xoxo_bot \
              -e TG_TOKEN=${{ secrets.TG_TOKEN }} \
              -v ${{ secrets.USER }}/workspace/aaa-xoxo-tgbot/data:/data \
              --restart unless-stopped \
              xoxo_bot

            echo "Deploy complete"
